name: atommover_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scikit-learn
  - numba::numba
  - xarray
  - ipykernel
  - matplotlib
  - pip:
      - imageio==2.36.1
      - pillow==11.1.0
